### IIM_Skills_Assignment

1. __Write a Python script that prints the numbers from 1 to 100, <br>
   but for multiples of three print "Fizz" instead of the number <br>
   and for the multiples of five print "Buzz".<br>
   For numbers which are multiples of both three and five, print "FizzBuzz".__

In [1]:
for x in range (1,101): #prints the numbers from 1 to 100
    if x % 3 == 0:
        print("Fizz")
    elif x % 5 == 0:
        print("Buzz")
    elif x % 3 == 0 and x % 5 == 0:
        print("FizzBuzz")
    else:
        print(x)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
Fizz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
Fizz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
Fizz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
Fizz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
Fizz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
Fizz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


2. __Write a Python script that calculates the factorial of a given number using aloop. <br>
   Prompt the user to enter a number and display its factorial.__

In [2]:
num = int(input ("Enter a number : "))
factorial = 1

if num < 0:
    print("No factorial for negative number")
elif num == 0:
    print("Factorial of 0 is 1")
else:
    for x in range (1, num + 1):
        factorial = factorial * x
    print (f"Factorial of {num} is {factorial}")

Enter a number :  6


Factorial of 6 is 720


3. __Write a Python script that takes a string input from the user <br>
   and prints whether the string is a palindrome. <br>
   Use conditional statements and loops in your solution.__

In [16]:
# With conditional statement

word = input("Enter a word : ")
word = word.lower()
reversed_word = word[::-1]

if word == reversed_word:
    print(f"{word} is a palindrome.")
else:
    print(f"{word} is a not palindrome.")


Enter a word :  Malayalam


malayalam is a palindrome.


In [17]:
# With conditional statement and loop

word = input("Enter a word : ")
word = word.lower()

length = len(word) - 1

for i in range (length // 2):
    if word[i] != word[- (i + 1)]:
        print(f"{word} is a not a palindrome.")
        break
else:
    print(f"{word} is a palindrome.")


Enter a word :  Sneha


sneha is a not a palindrome.


4. __Define a function in Python that takes a list of numbers <BR>
   and returns the sum of all even numbers in the list. <br>
   Use a lambda function to filter out the even numbers before summing them.__

In [23]:
# Enter numbers by user

def sum_of_even_numbers(numbers):
    return sum (filter(lambda x: x % 2 == 0, numbers))  # Filter out even numbers using a lambda function and sum them

input_numbers = input("Enter some numbers with space between numbers : ")
numbers = list(map(int, input_numbers.split()))  

sum_even = sum_of_even_numbers(numbers)

print(f"The sum of even numbers in the list is: {sum_even}")


Enter some numbers with space between numbers :  2 5 8 


The sum of even numbers in the list is: 10


In [24]:
# With given numbers

def sum_of_even_numbers (numbers):
    even_numbers        = lambda x : x % 2 == 0
    filter_even_numbers = filter(even_numbers)
    sum_even            = sum (filter_even_numbers)
    return (sum_even)

numbers = [1, 2, 3, 4, 5, 6]

print (sum_even)

10


In [6]:
# lambda function example
# Syntax is lambda arguments : expression

# lambda function that adds 10 to a given number (Add 10 to argument a, and return the result)

add_ten = lambda x: x + 10
print(add_ten(5))


15


In [26]:
# lambda function example

numbers = [1, 2, 3, 4, 5, 6]
even_numbers = list(filter(lambda x : x % 2 == 0, numbers))
print (even_numbers)

[2, 4, 6]


5. __Import the Titanic dataset (using pandas) into a Pandas DataFrame. <br>
   Perform basic operations such as displaying the first few rows, <br>
   checking for null values, and summarizing the DataFrame’s statistics__

In [31]:
import pandas as pd
import os

os.chdir(r"C:\Users\sneja\anaconda3\Lib\site-packages\bokeh_sampledata\_data")
print(os.getcwd())

C:\Users\sneja\anaconda3\Lib\site-packages\bokeh_sampledata\_data


In [28]:
#Import the Titanic dataset (using pandas) into a Pandas DataFrame

df = pd.read_csv(r"titanic_all.csv")

In [10]:
# displaying the first few rows

df.head()

name class    age     sex  \
0                   Allen, Miss Elisabeth Walton   1st  29.00  female   
1                    Allison, Miss Helen Loraine   1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton   1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)   1st  25.00  female   
4                  Allison, Master Hudson Trevor   1st   0.92    male   

   survived  
0         1  
1         0  
2         0  
3         0  
4         1

In [11]:
# checking for null values

df.isnull().sum()

name          0
class         0
age         557
sex           0
survived      0
dtype: int64

In [12]:
# summarizing the DataFrame’s statistics

df.describe()

age     survived
count  756.000000  1313.000000
mean    30.397989     0.342727
std     14.259049     0.474802
min      0.170000     0.000000
25%     21.000000     0.000000
50%     28.000000     0.000000
75%     39.000000     1.000000
max     71.000000     1.000000

In [13]:
# OVERALL CODES

print("First few rows of the dataset:")
print(df.head())
print("\nNull values in each column:")
print(df.isnull().sum())
print("\nSummary statistics of the dataset:")
print(df.describe())

First few rows of the dataset:
                                            name class    age     sex  \
0                   Allen, Miss Elisabeth Walton   1st  29.00  female   
1                    Allison, Miss Helen Loraine   1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton   1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)   1st  25.00  female   
4                  Allison, Master Hudson Trevor   1st   0.92    male   

   survived  
0         1  
1         0  
2         0  
3         0  
4         1  

Null values in each column:
name          0
class         0
age         557
sex           0
survived      0
dtype: int64

Summary statistics of the dataset:
              age     survived
count  756.000000  1313.000000
mean    30.397989     0.342727
std     14.259049     0.474802
min      0.170000     0.000000
25%     21.000000     0.000000
50%     28.000000     0.000000
75%     39.000000     1.000000
max     71.000000     1.000000


6. __Create a NumPy array with random numbers and perform the following operations: <br>
   calculate the mean, standard deviation, and reshape the array into a different dimension. <br>
   (No specific dataset required, use numpy)__

In [14]:
import numpy as np

# Create a 3x4 array with random numbers
array = np.random.randint(0,100, size = (3, 4))
print("Original array:")
print(array)

# Calculate the mean
mean_value = np.mean(array)
print("\nMean of the array:")
print(mean_value)

# Calculate the standard deviation
std_deviation = np.std(array)
print("\nStandard deviation of the array:")
print(std_deviation)

# Reshape the array into a different dimension (2x6)
reshaped_array = array.reshape(2, 6)
print("\nReshaped array (2x6):")
print(reshaped_array)


Original array:
[[15 67 98 78]
 [77 76 63 51]
 [67 22 56 72]]

Mean of the array:
61.833333333333336

Standard deviation of the array:
22.527144120421084

Reshaped array (2x6):
[[15 67 98 78 77 76]
 [63 51 67 22 56 72]]
